services:
  app:
    build:
      context: .

    working_dir: /workspace

    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules

    network_mode: host

    stdin_open: true
    tty: true
    init: true

    command: sleep infinity

volumes:
  node_modules: